version: '3.3'

services:
  db:
    image: postgres:13.0-alpine
    env_file:
      - ./.env
    volumes:
      - "./data:/var/lib/postgresql/data/"

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db