version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    env_file:
      - ./.env
    volumes:
      - "./data:/var/lib/postgresql/data/"
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
  nginx:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    env_file:
      - ./.env
    volumes:
      - "./dockerize/nginx.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - backend
      - db