add_superuser:
	docker compose -f docker-compose_prod.yml run --rm backend python manage.py add_superuser

migrate:
	docker compose -f docker-compose_prod.yml run --rm backend python manage.py migrate

production:
	docker compose -f docker-compose_prod.yml up -d