name: 'CI for Demo Front Library'

on:
    push:
        branches: [frontend_demo]
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: copy file via ssh password
          uses: appleboy/scp-action@v0.1.7
          with:
            host: ${{ secrets.FRONT_DEMO_SSH_HOST }}
            username: ${{ secrets.FRONT_DEMO_SSH_USERNAME }}
            key: ${{ secrets.FRONT_DEMO_SSH_KEY }}
            port: ${{ secrets.FRONT_DEMO_SSH_PORT }}
            source: "front_demo/"
            target: "/var/www/lib_front/"