name: 'CI for Demo Front Library'

on:
    push:
        branches: [frontend_demo]
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: copy file via ssh password
          uses: appleboy/scp-action@v0.1.7
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PASSWORD }}
            port: ${{ secrets.PORT }}
            source: "/front_demo/*"
            target: "/var/www/lib_front/"